name: Java CI with Maven and Docker Compose


on:
  schedule:
    - cron: '45 17 * * *'  # Runs at 4:45 PM UTC every day

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

# Install the docker compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

# Login into Docker compose
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

# Checks if DOcker composer is running
      - name: Check if Docker Compose is running
        id: check-docker-compose
        run: |
          docker-compose -f docker/docker-compose_grid.yml ps -q chrome firefox selenium-hub
          if [ $? -eq 0 ]; then
            echo "Docker Compose services are already running."
            echo "::set-output name=services_running::true"
          else
            echo "Docker Compose services are not running."
            echo "::set-output name=services_running::false"
          fi

      # Start Docker Compose services if not running
      - name: Start Docker Compose services if not running
        if: steps.check-docker-compose.outputs.services_running == 'false'
        run: |
          docker-compose -f docker/docker-compose_grid.yml up -d

      - name: Build with Maven
        run: >
          mvn clean test
          -Dmaven.test.failure.ignore=true

      - name: archive report artifact
        uses: actions/upload-artifact@v3
        with:
          name: sparkHTML
          path: ./reports/*.html

      - name: Stop Docker Compose services
        if: steps.check-docker-compose.outputs.services_running == 'false'
        run: |
          docker-compose -f docker/docker-compose_grid.yml down
          

      - name: Send Email Notification
        if: success() || failure()
        env:
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENTS: "chirag.ali47@gmail.com"

        run: |
          echo "Subject: Test Automation Completed" > email.txt
          echo "Hello Stakeholders," >> email.txt
          echo "" >> email.txt
          echo "The automated tests have completed." >> email.txt
          echo "You can view the test results at the following link:" >> email.txt
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> email.txt
          echo "" >> email.txt
          echo "Best regards," >> email.txt
          echo "Your Automation Team" >> email.txt
          cat email.txt | sendmail -t

      - name: Cleanup
        run: rm email.txt